### ISSUE TITLE
Support for hi-res monitors.

### ISSUE THREAD

**Issue by BirdInTheCity** [t-ho/ngx-gravatar#1]
First of all—thanks for putting this together!

To support hi-res monitors/phones, can the requested image size be separate from the img display size? Even when I hard-coded a width/height, the values get overridden.

`<img width=40 size="80"...>`

**Comment by t-ho** [comment]
Hi Brian,

Thank you for your feedback.

The feature has been implemented. Now, the `ratio` of requested image size to displayed size can be configured via `ratio` property or `forRoot()` method. By default, it is set to `2`.
