### ISSUE TITLE
Crome warning: "cookie associated with a cross-site resource"

### ISSUE THREAD

**Issue by Blume987** [t-ho/ngx-gravatar#11]
Hey there,

thank you for this easy to use module.

Got a Chrome warning because of missing attributes while setting cookie:

> A cookie associated with a cross-site resource at https://gravatar.com/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.

angular Version: 8.2.x
ngx-gravatar Version: 8.0.0
Chrome Version: Version 78.0.3904.108 (Official Build) (64-Bit)
OS: Mac OSX 10.15

**Comment by t-ho** [comment]
You can fix it by clearing the app cache & cookie.
