### ISSUE TITLE
Entry point 'ngx-gravatar' contains deep imports

### ISSUE THREAD

**Issue by blindsz** [t-ho/ngx-gravatar#13]
Hi. I have a warning using envy the message is 

"Entry point 'ngx-gravatar' contains deep imports into 'node_modules/ts-md5/dist/md5'"

Can we fixed this? I think envy doesn't like deep imports.

I think this is the issue.

![Untitled](https://user-images.githubusercontent.com/15309842/77084030-592ca680-6a39-11ea-90ba-ff533fb32baf.png)

**Comment by t-ho** [comment]
@blindsz 

This is related to [angular#35615](https://github.com/angular/angular/issues/35615) issue. You can safely ignore it ([angular#35683](https://github.com/angular/angular/pull/35683#issuecomment-592434035)) or follow [this instruction](https://github.com/angular/angular/issues/35615#issuecomment-592253747) to avoid the warning message. But, note that there is also a reported [issue](https://github.com/angular/angular/issues/35750) related to `ngcc.config.js`.

So I suggest you just simply ignore the warning message for now.

**Comment by blindsz** [comment]
Thank you for the clarification.

**Comment by petebacondarwin** [comment]
@t-ho - you can now also add a "package-level" `ngcc.config.js` file to the `ngx-gravatar` npm package that ngcc will read, where you can tell ngcc to ignore these deep-imports for your library. See https://github.com/angular/angular/issues/35750#issuecomment-608368344

**Comment by t-ho** [comment]
Thank you very much, @petebacondarwin

**Comment by blindsz** [comment]
> Thank you very much, @petebacondarwin

Will this be updated??

**Comment by petebacondarwin** [comment]
My PR is in review. If it gets merged today or tomorrow, then it should be in the 9.1.1 release on later this week.

**Comment by blindsz** [comment]
> My PR is in review. If it gets merged today or tomorrow, then it should be in the 9.1.1 release on later this week.

I cant see you your PR

**Comment by petebacondarwin** [comment]
It is this one - https://github.com/angular/angular/pull/36423 - which got merged yesterday.
So it will be in the next patch release.

In your case, @blindsz, this PR makes no real difference to you I think. When you say `envy` I assume you mean `ivy`? And also I assume that you are actually writing an application (not a library) that uses `ngx-gravatar` right? In that case, you can already configure ngcc to ignore the deep imports that `ng-gravatar` is doing via a "project level" ngcc.config.js file.

What might happen, though is that `ngx-gravatar` might add its own "package level" ngcc.config.js file to its published package that will hide these warnings on your behalf.

**Comment by blindsz** [comment]
> It is this one - [angular/angular#36423](https://github.com/angular/angular/pull/36423) - which got merged yesterday.
> So it will be in the next patch release.
> 
> In your case, @blindsz, this PR makes no real difference to you I think. When you say `envy` I assume you mean `ivy`? And also I assume that you are actually writing an application (not a library) that uses `ngx-gravatar` right? In that case, you can already configure ngcc to ignore the deep imports that `ng-gravatar` is doing via a "project level" ngcc.config.js file.
> 
> What might happen, though is that `ngx-gravatar` might add its own "package level" ngcc.config.js file to its published package that will hide these warnings on your behalf.

Thanks! It's strange I don't remember putting envy there instead of ivy. Anyways this is not big deal. I just wanted to remove the warning. I'll just wait for author of the package to update this inside its package. I will close this now. Thanks!

**Comment by petebacondarwin** [comment]
Thanks!
