### ISSUE TITLE
Error Can't bind to 'email' since it isn't a known property of 'img'

### ISSUE THREAD

**Issue by pgupta-infoobjects** [t-ho/ngx-gravatar#16]
I recently used ngx-gravatar and trying to bind property like the below image. this is throwing error. 

![image](https://user-images.githubusercontent.com/21075068/84867574-00e95d00-b099-11ea-9550-22bb4817fbe7.png)

**Comment by t-ho** [comment]
Hi @pgupta-infoobjects,

You need to import `GravatarModule` in your root `AppModule`. Please see the docs [here](https://tdev.app/ngx-gravatar#getting-started)

**Comment by NicoJuicy** [comment]
Just mentioning, it could be because you installed the wrong version according to your angular version.
