### ISSUE TITLE
Bind error

### ISSUE THREAD

**Issue by bryanllewis** [t-ho/ngx-gravatar#2]
When attempting to set this up, I get the following message to the console:

Uncaught Error: Template parse errors:
Can't bind to 'email' since it isn't a known property of 'img'.
<img ngxGravatar [ERROR ->][email]="user.email" [src]="user.avatar" class="img-thumbnail rounded-circle" alt="">

**Comment by john-sec** [comment]
You need to import `GravatarModule` in the module that declares the component using `ngxGravatar` directive.
