### ISSUE TITLE
Electron issue

### ISSUE THREAD

**Issue by mstojevski** [t-ho/ngx-gravatar#9]
When used with combination of electron and angular, there is issue with protocol.
It is not set to neither https or http but "//" and image can't be downloaded.

**Comment by DanielFrugoni** [comment]
when I try to use background get an error.
this is ok:
win = new electron_1.BrowserWindow({
        x: 0,
        y: 0,
        width: size.width,
        height: size.height,
        webPreferences: {
            nodeIntegration: true,
        },
    });
Error here
win = new electron_1.BrowserWindow({
        x: 0,
        y: 0,
        width: size.width,
        height: size.height,
        backgroundColor: '#2e2c29',  // windows will not load after this
        webPreferences: {
            nodeIntegration: true,
        },
    });

**Comment by OlexandrPopov** [comment]
@t-ho What do you think about adding a property to the config that allows to set protocol?

**Comment by OlexandrPopov** [comment]
@mstojevski @OwnedTom Would you mind making a pull request with your fix?

**Comment by t-ho** [comment]
I have updated the lib.
